import NavBar from "@/components/NavBar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import { Copyright } from "lucide-react";
import CopyRigt from "@/components/CopyRigt";
import Providers from "./providers";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dine Market",
  description: "Generated by Saad Ahmad Khan",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>


          <NavBar />
          {children}
          <Footer />
          <CopyRigt />
       
        </Providers>
        
      </body>
    </html>
  );
}
