import { Product } from "./types";

export const product: Product[] = [
    {
        id: 1,
        title: "Man",
        image: ["/1/promo1.jpg" , "/1/promo2.jpg"],
        slug: "Man-printed-tee-1",
        price: 150,
        discount: 0,
        category: "man",
        description: "Man T-shirt and pant",
        size: ["S", "M" , "L", "XL"],
        color: ["#ffffff", "#000000", "#e6000"],
        qty: 1,
    },
    {
        id: 2,
        title: "Man",
        image: ["/1/promo1.jpg" , "/1/promo2.jpg"],
        slug: "Man-printed-tee-2",
        price: 150,
        discount: 30,
        category: "man",
        description: "Man T-shirt and pant",
        size: ["S", "M" , "L", "XL"],
        color: ["#ffffff", "#000000", "#e6000"],
        qty: 1,
    },
    {
        id: 3,
        title: "Man",
        image: ["/1/promo1.jpg" , "/1/promo2.jpg"],
        slug: "Man-printed-tee-3",
        price: 150,
        discount: 50,
        category: "man",
        description: "Man T-shirt and pant",
        size: ["S", "M" , "L", "XL"],
        color: ["#ffffff", "#000000", "#e6000"],
        qty: 1,
    },
    {
        id: 4,
        title: "Kids",
        image: ["/1/promo1.jpg" , "/1/promo2.jpg"],
        slug: "Man-printed-tee-4",
        price: 150,
        discount: 10,
        category: "kids",
        description: "Man T-shirt and pant",
        size: ["S", "M" , "L", "XL"],
        color: ["#ffffff", "#000000", "#e6000"],
        qty: 1,
    },
    {
        id: 5,
        title: "Kids",
        image: ["/1/promo1.jpg" , "/1/promo2.jpg"],
        slug: "Man-printed-tee-5",
        price: 150,
        discount: 0,
        category: "kids",
        description: "Man T-shirt and pant",
        size: ["S", "M" , "L", "XL"],
        color: ["#ffffff", "#000000", "#e6000"],
        qty: 1,
    },
    {
        id: 6,
        title: "Woman",
        image: ["/1/promo1.jpg" , "/1/promo2.jpg"],
        slug: "Man-printed-tee-6",
        price: 1150,
        discount: 30,
        category: "woman",
        description: "Man T-shirt and pant",
        size: ["S", "M" , "L", "XL"],
        color: ["#ffffff", "#000000", "#e6000"],
        qty: 1,
    },
    {
        id: 7,
        title: "New Boarn",
        image: ["/1/promo1.jpg" , "/1/promo2.jpg"],
        slug: "Man-printed-tee-7",
        price: 1150,
        discount: 30,
        category: "new-born",
        description: "Man T-shirt and pant",
        size: ["S", "M" , "L", "XL"],
        color: ["#ffffff", "#000000", "#e6000"],
        qty: 1,
    },
]